force-app/main/default/objects/Cliente__c/Cliente__c.object-meta.xml
<CustomObject>
    <label>Cliente</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cliente__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cliente__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cliente Ativo</fullName>
            </value>
            <value>
                <fullName>Cliente Inativo</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClienteController.cls
public with sharing class ClienteController {
   
    @AuraEnabled(cacheable=true)
    public static List<Cliente__c> buscarClientes(){

        return[
            SELECT Id,
                   Name,
                   Empresa__c,
                   Status__c
            FROM Cliente__c
        ];
    }

    @AuraEnabled
    public static void criarCliente(
    String nome,
    String empresa,
    String email,
    String status
){
    Cliente__c cliente = new Cliente__c();

    cliente.Name = nome;
    cliente.Empresa__c = empresa;
    cliente.Email__c = email;
    cliente.Status__c = status;

    insert cliente;
}

}